// Data Mesjid di Kota Bandung dengan tambahan fasilitas, lokasi, dan kode pos
const mosqueData = [
  {
    id: 1,
    name: "Mesjid Agung Bandung",
    lat: -6.92169,
    lng: 107.60614,
    image: "https://i.ytimg.com/vi/Jp4EIKmTtNc/maxresdefault.jpg",
    address: "Jl. Asia Afrika No.3, Balonggede, Kec. Regol, Kota Bandung, Jawa Barat",
    postalCode: "40251",
    // Tambahkan/Ubah fasilitas di sini
    facilities: [ "Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat Utama",
      "Area Sholat Wanita Terpisah",
      "Tempat Wudhu Modern",
      "Toilet Bersih",
      "Area Parkir Luas (Mobil & Motor)",
      "Menara Pandang",
      "Pusat Informasi Islami",
      "Taman dan Area Hijau",
      "Layanan Haji & Umrah",
    ],
  },
  {
    id: 2,
    name: "Al-Ukhuwwah Great Mosque",
    lat: -6.910825,
    lng: 107.608772,
    image:
      "https://plongsite.wordpress.com/wp-content/uploads/2021/09/20210903_0927246123992465847923465.jpg?w=1024",
    address: "Jl. Wastukencana No.27, Babakan Ciamis, Kec. Sumur Bandung, Kota Bandung, Jawa Barat",
    postalCode: "40117",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat Utama",
      "Tempat Wudhu",
      "Toilet",
      "Area Parkir",
      "Perpustakaan",
      "Aula Serbaguna",
    ],
  },
  {
    id: 3,
    name: "Mesjid Agung Trans Studio",
    lat: -6.925936,
    lng: 107.635456,
    image:
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjbj7H98zBkW54bmVds-yrKVKc_BClW-u-gEY4upGu82rxbMrjKiCPGgIBep4l3oaWqMWg8UQBlenBaTXOcmqyxBMfECLbglKcXzlYF5zkBj95DA1MIhX3qFyxMC8oNLhcoU4luVYM-hc4p/s1600/masjidtrans+%25281%2529.jpg",
    address: "Jl. Gatot Subroto No.289, Cibangkong, Kec. Batununggal, Kota Bandung, Jawa Barat",
    postalCode: "40273",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat Utama",
      "Area Sholat Wanita Terpisah",
      "Tempat Wudhu",
      "Toilet",
      "Area Parkir Basement",
      "Akses Langsung ke Mall",
      "AC Penuh",
      "Restoran/Food Court di area sekitar",
    ],
  },
  {
    id: 4,
    name: "PUSDAI Jawa Barat",
    lat: -6.90012,
    lng: 107.625965,
    image: "https://live.staticflickr.com/8188/8416526710_a81da70dec_b.jpg",
    address: "Jl. Diponegoro No.63, Cihaur Geulis, Kec. Cibeunying Kaler, Kota Bandung, Jawa Barat",
    postalCode: "40122",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat Utama (Kapasitas Besar)",
      "Area Sholat Wanita Terpisah",
      "Tempat Wudhu Modern",
      "Toilet",
      "Area Parkir Luas",
      "Gedung Pertemuan/Aula",
      "Pusat Kajian Islam",
      "Penerbitan Islami",
      "Koperasi",
      "Madrasah/Sekolah",
    ],
  },
  {
    id: 5,
    name: "Mesjid Daarut Tauhiid",
    lat: -6.863527,
    lng: 107.589919,
    image:
      "https://www.daaruttauhiid.org/wp-content/uploads/2019/12/Akhir-2019-Ini-Progres-Wakaf-Masjid-3-in-1_Daarut-Tauhiid.jpg",
    address: "Jl. Gegerkalong Girang No.33, Gegerkalong, Kec. Sukasari, Kota Bandung, Jawa Barat",
    postalCode: "40154",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat Utama",
      "Area Sholat Wanita",
      "Tempat Wudhu",
      "Toilet",
      "Area Parkir",
      "Koperasi Syariah",
      "Pondok Pesantren",
      "Media Dakwah (TV, Radio, dll.)",
      "Program Wakaf",
    ],
  },
  {
    id: 6,
    name: "Mesjid Al-Imtizaj",
    lat: -6.919425,
    lng: 107.607864,
    image:
      "https://www.wowkeren.com/display/images/photo/2019/02/19/00244960_6.jpg",
    address: "Jl. Babakan Ciparay No.11, Babakan Ciparay, Kec. Babakan Ciparay, Kota Bandung, Jawa Barat",
    postalCode: "40223",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Arsitektur Unik (Akulturasi Budaya)",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Area Parkir Terbatas",
      "Pusat Kegiatan Budaya",
    ],
  },
  {
    id: 7,
    name: "Mesjid Lautze 2",
    lat: -6.918092,
    lng: 107.612306,
    image:
      "https://asset.kompas.com/crops/2jGUEgrzc3yA9uBZJn3P-EJT8mQ=/0x67:1600x1134/750x500/data/photo/2023/03/06/640583e6d5337.jpeg",
    address: "Jl. Panjunan No.42, Panjunan, Kec. Astanaanyar, Kota Bandung, Jawa Barat",
    postalCode: "40242",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Pusat Dakwah & Pembinaan Mualaf",
      "Perpustakaan",
    ],
  },
  {
    id: 8,
    name: "Mesjid Al-Furqan",
    lat: -6.863105,
    lng: 107.593506,
    image: "https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2021/11/06/202975307.jpg",
    address: "Jl. Dr. Setiabudi No.229, Isola, Kec. Sukasari, Kota Bandung, Jawa Barat",
    postalCode: "40154",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Area Parkir",
      "Berada di Lingkungan Kampus (UPI)",
      "Area Diskusi/Kajian",
    ],
  },
  {
    id: 9,
    name: "Masjid Besar Cipaganti",
    lat: -6.89458,
    lng: 107.602345,
    image:
      "https://cloud.jpnn.com/photo/jatim/news/normal/2022/03/26/bagian-dalam-masjid-besar-cipaganti-yang-masih-dijaga-keasli-2i1q.jpg",
    address: "Jl. Cipaganti No.85, Pasteur, Kec. Sukajadi, Kota Bandung, Jawa Barat",
    postalCode: "40161",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat Utama",
      "Area Sholat Wanita",
      "Tempat Wudhu",
      "Toilet",
      "Arsitektur Klasik",
      "Halaman Luas",
    ],
  },
  {
    id: 10,
    name: "Salman ITB Mosque",
    lat: -6.893706,
    lng: 107.611182,
    image:
      "https://dewilailypurnamasari.wordpress.com/wp-content/uploads/2024/02/img-20240205-wa0011.jpg",
    address: "Jl. Ganeca No.7, Lb. Siliwangi, Kec. Coblong, Kota Bandung, Jawa Barat",
    postalCode: "40132",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat Utama",
      "Area Sholat Wanita Terpisah",
      "Tempat Wudhu",
      "Toilet",
      "Perpustakaan Salman",
      "Pusat Kegiatan Mahasiswa Muslim",
      "Unit Kegiatan Keislaman",
      "Kafetaria",
      "Panti Asuhan",
    ],
  },
  {
    id: 11,
    name: "Mesjid Mungsolkanas",
    lat: -6.891751,
    lng: 107.604797,
    image:
      "https://cloud.jpnn.com/photo/arsip/normal/2022/06/21/masjid-mungsolkanas-yang-merupakan-masjid-tertua-di-kota-ban-cnw0.jpg",
    address: "Jl. Cihampelas No.143, Cipaganti, Kec. Coblong, Kota Bandung, Jawa Barat",
    postalCode: "40131",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Masjid Bersejarah",
    ],
  },
  {
    id: 12,
    name: "Masjid Al-Murabbi",
    lat: -6.879499,
    lng: 107.583468,
    image:
      "https://lh5.googleusercontent.com/p/AF1QipPOCLgc9MC_zqrSdlC4kZSEFpHA_Mgv-r5-b_sO=w426-h240-k-no",
    address: "Jl. Sutami No.2, Sukagalih, Kec. Sukajadi, Kota Bandung, Jawa Barat",
    postalCode: "40163",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Kajian Rutin",
      "Pusat Dakwah",
    ],
  },
  {
    id: 13,
    name: "Masjid At-Taufiq Gegerkalong",
    lat: -6.86434,
    lng: 107.591293,
    image:
      "https://blue.kumparan.com/image/upload/fl_progressive,fl_lossy,c_fill,q_auto:best,w_640/v1634025439/018143395683a16a58dabc56c76eddcb.jpg",
    address: "Jl. Gegerkalong Hilir No.105, Gegerkalong, Kec. Sukasari, Kota Bandung, Jawa Barat",
    postalCode: "40153",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Madrasah/Pendidikan Islam",
    ],
  },
  {
    id: 14,
    name: "Mesjid Habiburrahman",
    lat: -6.898969,
    lng: 107.585126,
    image: "https://habiburrahman.org/img/home/home.png",
    address: "Jl. Pajajaran No.155, Husein Sastranegara, Kec. Cicendo, Kota Bandung, Jawa Barat",
    postalCode: "40174",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat Luas",
      "Tempat Wudhu",
      "Toilet",
      "Pusat Kegiatan Keagamaan",
      "Area Parkir",
    ],
  },
  {
    id: 15,
    name: "Masjid Al-Lathiif",
    lat: -6.908063,
    lng: 107.627868,
    image:
      "https://hidayatullah.com/wp-content/uploads/2018/06/Masjid-al-Lathif1.jpg",
    address: "Jl. Samoja No.32, Kacapiring, Kec. Batununggal, Kota Bandung, Jawa Barat",
    postalCode: "40271",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Kajian Pemuda",
      "Pusat Dakwah",
    ],
  },
  {
    id: 17,
    name: "Mesjid Al Mu'min",
    lat: -6.913328,
    lng: 107.601731,
    image:
      "https://weddinghnr.com/wp-content/uploads/2021/10/IMG_6745-Al-Mumin-Pegangsaan2-Klp-Gading-Jakarta-utara.jpg",
    address: "Jl. Sukajadi No.174, Pasteur, Kec. Sukajadi, Kota Bandung, Jawa Barat",
    postalCode: "40162",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Pusat Komunitas"
    ],
  },
  {
    id: 18,
    name: "Mesjid At-Taqwa KPAD",
    lat: -6.866099,
    lng: 107.586208,
    image: "https://i.ytimg.com/vi/BlIbwufZR6s/maxresdefault.jpg",
    address: "Jl. Sarimanah I No.4, Sariwangi, Kec. Parongpong, Kabupaten Bandung Barat, Jawa Barat",
    postalCode: "40559",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Lingkungan Perumahan"
    ],
  },
  {
    id: 19,
    name: "Masjid As Safiir STP Bandung",
    lat: -6.868486,
    lng: 107.594019,
    image:
      "https://awsimages.detik.net.id/community/media/visual/2022/04/26/masjid-al-safar-di-rest-area-ini-diarsiteki-ridwan-kamil_169.jpeg?w=650&q=90",
    address: "Jl. Dr. Setiabudi No.229, Isola, Kec. Sukasari, Kota Bandung, Jawa Barat",
    postalCode: "40154",
    // Tambahkan/Ubah fasilitas di sini
    facilities: [
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Desain Modern",
      "Berada di Area Rest Area Tol",
    ],
  },
  {
    id: 20,
    name: "Masjid Al-Muttaqin (Gedung Sate)",
    lat: -6.902249,
    lng: 107.617924,
    image:
      "https://i.pinimg.com/736x/5f/75/7f/5f757f5aef61b492214d94ba3dee5471.jpg",
    address: "Jl. Diponegoro No.22, Citarum, Kec. Bandung Wetan, Kota Bandung, Jawa Barat",
    postalCode: "40115",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Lokasi Strategis (Dekat Gedung Sate)",
    ],
  },
  {
    id: 21,
    name: "Masjid Husnul Khotimah",
    lat: -6.86024,
    lng: 107.587169,
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AC9h4np1AU4BJjQb30U07eEoI0fdZEbcqpdeKtuESwKjd-8tFj1oHBqparHWNWdd88k_Al02f1P1nZm0r2PulYce-dhbwoGBN2Eu64xJXWFRkIup7YZUVbMNR-V4vdxZh9ZPd_mrVaI=s1360-w1360-h1020",
    address: "Jl. Gegerkalong Hilir No.105, Gegerkalong, Kec. Sukasari, Kota Bandung, Jawa Barat",
    postalCode: "40153",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet"
    ],
  },
  {
    id: 22,
    name: "Masjid Raya Al Jabbar",
    lat: -6.948114,
    lng: 107.703501,
    image:
      "https://bolulembang.co.id/wp-content/uploads/2023/02/Masjid-Raya-Al-Jabbar_-Daya-Tarik-Sejarah-Tiket-Masuk_Img2.png",
    address: "Jl. Cimincrang No.14, Cimincrang, Kec. Gedebage, Kota Bandung, Jawa Barat",
    postalCode: "40292",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat Utama (Sangat Luas)",
      "Area Sholat Wanita Terpisah",
      "Tempat Wudhu Modern",
      "Toilet Banyak",
      "Area Parkir Raksasa",
      "Museum Sejarah Islam Jawa Barat",
      "Taman Air dan Kolam Retensi",
      "Area Edukasi",
      "Toko Oleh-oleh",
      "Akses Mudah dari Tol",
    ],
  },
  {
    id: 23,
    name: "Masjid Besar Baiturrahman",
    lat: -6.91269,
    lng: 107.623947,
    image: "https://lh3.googleusercontent.com/gps-cs-s/AC9h4notb5IA33ajFzYXw0o68DmO3IF5sIaTE-3K3NjjMFfHBF_J5eUd7BUzW6tJWWNzeLYAG3LzKJSfaRdjgtgm7z7Fh5IVePOrhEu-94vOMLI-cMXKKgtBMaDywN6gnRRqP1L14be4=s1360-w1360-h1020",
    address: "Jl. Cikini No.14, Antapani Kidul, Kec. Antapani, Kota Bandung, Jawa Barat",
    postalCode: "40291",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Aula"
    ],
  },
  {
    id: 24,
    name: "Masjid Darul Ihsan Telkom Corporate University",
    lat: -6.872273,
    lng: 107.588803,
    image:
      "https://pendidikpembebas.wordpress.com/wp-content/uploads/2024/06/img-20240607-wa00132010225518611372964.jpg",
    address: "Jl. Gegerkalong Hilir No.47, Gegerkalong, Kec. Sukasari, Kota Bandung, Jawa Barat",
    postalCode: "40153",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Berada di Komplek Telkom Corporate University",
    ],
  },
  {
    id: 25,
    name: "Masjid Nurul Huda",
    lat: -6.859506,
    lng: 107.595378,
    image:
      "https://menara.baznas.go.id/attachments/masjid-musholla/foto-thumbnail/M347130018052024146-masjid-nurul-huda-glagah-20240611203212.jpeg",
    address: "Jl. Gegerkalong Girang, Isola, Kec. Sukasari, Kota Bandung, Jawa Barat",
    postalCode: "40154",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet"
    ],
  },
  {
    id: 26,
    name: "Masjid Jami Al-Hikmah Panorama",
    lat: -6.866533,
    lng: 107.597012,
    image: "https://mesjidku.com/wp-content/uploads/2024/09/2022-09-03.jpg",
    address: "Jl. Panorama, Isola, Kec. Sukasari, Kota Bandung, Jawa Barat",
    postalCode: "40154",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Lingkungan Perumahan"
    ],
  },
  {
    id: 27,
    name: "Al-Aqsa Mosque",
    lat: -6.870801,
    lng: 107.580705,
    image: "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nrksl9BvFt3WA3ldONus9VxCZy9vgGhXSaqgCmPkIVsWQNYen4IDMSLhtLuUoC-84A4mn5GZ0J0Y8x3STduX1jTMBtbmY3BBzn7nJcM554fVidXnUHO_e5bvO5W3Xr1O9qRbyH8Lw=s1360-w1360-h1020",
    address: "Jl. Sari Asih No.11, Sariwangi, Kec. Parongpong, Kabupaten Bandung Barat, Jawa Barat",
    postalCode: "40559",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet"
    ],
  },
  {
    id: 28,
    name: "Mosque Mujahidin",
    lat: -6.93059,
    lng: 107.619367,
    image:
      "https://www.volunteer.gov.sg/images/default-source/opportunity/13342aaa-71c0-4ee4-8338-c8259ff18c5e.jpg?Status=Master&sfvrsn=ae03a1cc_3",
    address: "Jl. Siliwangi No.1, Cipadung Kidul, Kec. Panyileukan, Kota Bandung, Jawa Barat",
    postalCode: "40294",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Kegiatan Sosial"
    ],
  },
  {
    id: 29,
    name: "Masjid Miftahul Iman",
    lat: -6.85472,
    lng: 107.593576,
    image: "https://lh3.googleusercontent.com/gps-cs-s/AC9h4noopno3GUJX6eXlpOXJY2y23weuyMbAevYnmtpFbKQl23nrtLhu-Zv3oMzx_All8uJAtg1-FeRuZmP0rL5HLq-1eWbP_Np2S-pyFhqULaHXwbr5-ui1-C1EZz1xP5ze56bIasbmJg=s1360-w1360-h1020",
    address: "Jl. Gegerkalong Girang, Isola, Kec. Sukasari, Kota Bandung, Jawa Barat",
    postalCode: "40154",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet"
    ],
  },
  {
    id: 30,
    name: "Al-Jihad Mosque, Unpad",
    lat: -6.892213,
    lng: 107.61666,
    image:
      "https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/p2/197/2024/11/09/9-Masjid-Al-Jihad_LAN-4-824404829.jpg",
    address: "Jl. Dipati Ukur No.35, Lebakgede, Kec. Coblong, Kota Bandung, Jawa Barat",
    postalCode: "40132",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Berada di Lingkungan Kampus (Unpad)",
      "Area Diskusi",
    ],
  },
  {
    id: 33,
    name: "Masjid At Taqwa",
    lat: -6.854453,
    lng: 107.596718,
    image:
      "https://upload.wikimedia.org/wikipedia/id/thumb/c/c7/MASJID-ATTAQWA.jpeg/1200px-MASJID-ATTAQWA.jpeg",
    address: "Jl. Gegerkalong Hilir No.105, Gegerkalong, Kec. Sukasari, Kota Bandung, Jawa Barat",
    postalCode: "40153",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Pusat Kegiatan Masyarakat"
    ],
  },
  {
    id: 34,
    name: "Masjid MUI Kota Bandung",
    lat: -6.89132,
    lng: 107.625625,
    image: "https://lh3.googleusercontent.com/proxy/kR6srJPtoIDd_i4LX1MAL0jWQRraX-jinMDDU3gvGdE2yca7L_IQAucyAafcYK0tAT7ee9ky-aLONiru6fnX5je7bFDb8_x49hJL67TQmyQmKXN6z4eHJUpLrZzTVuLHxlyxeuDI9Nej2Xp3FpzpMmOJ56Xsvobn1smGag=s1360-w1360-h1020",
    address: "Jl. Cisangkuy No.27, Citarum, Kec. Bandung Wetan, Kota Bandung, Jawa Barat",
    postalCode: "40115",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Kantor MUI"
    ],
  },
  {
    id: 35,
    name: "MASJID BAABUL FIRDAUS (LDII)",
    lat: -6.867601,
    lng: 107.59303,
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nppEXxFpuumqTzLeFZP0qIqWsWgI5WPSLPRbhORJflorl91fmOL_w__jwq09J38Uyk6OniK-ntkFQ7YlCDzGgPfFG1wS1lv4h-EK1MXtHgcnxnUq06suGUY9VPkAN6GRbdj28El=s1360-w1360-h1020",
    address: "Jl. Gegerkalong Hilir No.105, Gegerkalong, Kec. Sukasari, Kota Bandung, Jawa Barat",
    postalCode: "40153",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Pusat Dakwah LDII"
    ],
  },
  {
    id: 36,
    name: "Mesjid Istiqama",
    lat: -6.904803,
    lng: 107.621962,
    image:
      "https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/ayobandung/images-bandung/post/articles/2017/05/31/20192/istiqamah.jpg",
    address: "Jl. Citarum No.20, Citarum, Kec. Bandung Wetan, Kota Bandung, Jawa Barat",
    postalCode: "40115",
    // Tambahkan/Ubah fasilitas di sini
    facilities: ["Menyediakan berbagai fasiliatas diantaranya",
      "Area Sholat",
      "Tempat Wudhu",
      "Toilet",
      "Aula Besar",
      "Kegiatan Sosial"
    ],
  },
];
// Export data untuk digunakan di main.js
window.mosqueData = mosqueData;
